spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_order
    username: usr_order
    password: pass_order
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9080
  servlet:
    context-path: /api

services:
  payment-service:
    host: http://localhost:9090
    endpoints:
      payment: /api/v1/payment
